### ISSUE TITLE
Few-shot learning

### ISSUE THREAD

**Issue by YahyaAltun** [linux-china/chatgpt-spring-boot-starter#14]
Hello, good day. I am trying to build an application using the library you've developed.
 
Each method should have its own prompt. The prompt from the user should run my method prompt first. Then the method should work and I should get an answer.

 I have read the README file, but I am having trouble achieving this. Could you please assist me?

**Comment by linux-china** [comment]
could you share your demo repo on GitHub?  and I can take a look. Thanks

**Comment by YahyaAltun** [comment]
For example, when the send_email method runs, I want to run a prompt where I want it translated to German. When the read_email method is run, I want it to be translated into Turkish and run this prompt before the method.

https://github.com/YahyaAltun/chatbotdemo

**Comment by linux-china** [comment]
@YahyaAltun  how about Spring AOP?  you can use AOP to intercept any method call.

**Comment by YahyaAltun** [comment]
I tried spring aop but it didn't give the result i wanted. Chatgpt answered the question when this line;

  // display reply combined text with function call
      System.out.println(response.getReplyCombinedText());

I want to manipulating chatgpt answers. How can i use prompt.properties for to add a prompt to the user prompt. Thanks

**Comment by YahyaAltun** [comment]
I got it and can i ask another question? 

 The conversation consists of only one question and one answer. I want it to respond to my new question by recalling the previous answer and the previous question.(as in chatgpt)
 
Should I save the questions and answers to the database and send them in every new request, or is there another way to do it?
