### ISSUE TITLE
Role can only by "system", "user" or "assistant", so should be an enum

### ISSUE THREAD

**Issue by stephanj** [linux-china/chatgpt-spring-boot-starter#3]
public ChatMessage(String role, String content) {
        this.role = role;
        this.content = content;
    }
    
The Chat Message Role can only by "system", "user" or "assistant", so make it an enum please.

**Comment by linux-china** [comment]
got. I will fix this problem

**Comment by linux-china** [comment]
Fixed by https://github.com/linux-china/chatgpt-spring-boot-starter/commit/f84c4d10dd885e2f1f7c30ae050d6e49fdd9482c
