### ISSUE TITLE
proxy

### ISSUE THREAD

**Issue by heeloo0212** [linux-china/chatgpt-spring-boot-starter#5]
可以在调用openai接口时加一层代理吗，国内使用翻墙调用openai接口会连接超时

**Comment by linux-china** [comment]
请参考 https://github.com/linux-china/chatgpt-spring-boot-starter/blob/main/src/test/java/org/mvnsearch/chatgpt/demo/OpenAIProxyController.java  

```java

@RestController
public class OpenAIProxyController {
    @Autowired
    private ChatGPTService chatGPTService;
    
    @PostMapping("/v1/chat/completions")
    public Publisher<ChatCompletionResponse> completions(@RequestBody ChatCompletionRequest request) {
        if (request.getStream() == null || !request.getStream()) {
            return chatGPTService.chat(request);
        } else {
            return chatGPTService.stream(request);
        }
    }
}
```

**Comment by linux-china** [comment]
Done in version 0.2.1

**Comment by jingxiang** [comment]
@linux-china 这个如何设置代理？

**Comment by linux-china** [comment]
如下配置里应该可以的。 

https:

```
JAVA_FLAGS=-Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=8888
```

http: 
```
JAVA_FLAGS=-Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=8888
```

**Comment by linux-china** [comment]
最后说一下，使用该starter做代理，有点重。 有很多种方案做OpenAI代理，一个简单的Node.js就可以。

**Comment by heeloo0212** [comment]
HttpClient httpClient = HttpClient.create().proxy(proxy -> proxy.type(ProxyProvider.Proxy.HTTP).host("127.0.0.1").port(7890));
            webClient = WebClient.builder()
                    .clientConnector(new ReactorClientHttpConnector(httpClient))
                    .defaultHeader("Authorization", "Bearer " + openaiApiKey)
                    .baseUrl(baseUrl)
                    .build();
可以尝试这样，我本地能调用了
